{% extends "geosite/maps/base.yml" %}

{% block title %}
title: SPARC
{% endblock %}

{% block pages %}{% verbatim %}
pages:
  explore: "/explore"
  country_detail: "/country/{{ iso3 }}"
  countryhazard_detail: "/country/{{ iso3 }}/hazard/{{ hazard }}"
  countryhazardmonth_detail: "/country/{{ iso3 }}/hazard/{{ hazard }}/month/{{ month }}"
{% endverbatim %}{% endblock %}

{% block baselayers %}
baselayers:
  - id: "osm_humanitarian"
    title: OpenStreetMap / Humanitarian
    description: "OpenStreetMap Basemap, Humanitarian Style"
    source:
      name: "OpenStreetMap"
      attribution: "&copy; <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap</a>"
      url: "http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png"
    legend:
      label: "OpenStreetMap / Humanitarian"
  - id: "osm"
    title: "OpenStreetMap"
    description: "OpenStreetMap Basemap, Standard Style"
    source:
      name: "OpenStreetMap"
      attribution: "&copy; <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap</a>"
      url: "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
    legend:
      label: "OpenStreetMap"
{% endblock %}

{% block legendlayers %}
legendlayers:
  - osm_humanitarian
  - osm
{% endblock %}

{% block renderlayers %}
renderlayers:
  - osm
  - osm_humanitarian
{% endblock %}
