---
name: "SPARC 2.x"
plugins:
  - base
  - modal
  - breadcrumbs
  - calendar
  - legend
  - filter
  - map
  - map_map
  - sparc_sidebar
  - main
dependencies:
  - "/home/vagrant/geosite-framework-django.git/geosite/static/geosite/src/geosite"
