---
name: "SPARC 2.x"
path:
  geosite: "./src/geosite"
less:
  pre:
    - "./src/geosite/global/sparc.less"
  paths:
    - "./src/geosite/global"
  outfile: "main.css"
  dest: "./build/css/"
plugins:
  - breadcrumbs
  - calendar
  - filter
  - map_map
  - sparc_sidebar
  - main
  - sparc_welcome
dependencies:
  production:
    javascript:
      - "./src/js/main/*.js"
      - "./build/templates/templates.js"
    templates:
      - "./src/templates/*.html"
    project:
      - "/home/vagrant/geosite-framework-django.git/geosite/static/geosite/config.yml"
  test:
    javascript:
      - "./src/js/main/*.js"
      - "./src/js/polyfill/*.js"
compiler:
  list:
    - name: "monkeypatch_js"
      type: "js"
      src: "./src/js/monkeypatch/*.js"
      outfile: "monkeypatch.js"
      dest: "./build/js/"
    - name: polyfill_js
      type: js
      src: "./src/js/polyfill/*.js"
      outfile: "polyfill.js"
      dest:  "./build/js/"
